export const base = 20000;
export const achievements = [
  { id: 1, name: 'Allow Cookies?' },
  { id: 2, name: 'Backpack Tourist' },
  { id: 3, name: 'Bearhugger' },
  { id: 4, name: 'Bone Brother' },
  { id: 5, name: 'Chorister' },
  { id: 6, name: 'Fountain of Life' },
  { id: 7, name: 'Here, Fishy Fishy!' },
  { id: 8, name: 'Honorary Barbarian' },
  { id: 9, name: 'Huntsman' },
  { id: 10, name: 'Just in Time' },
  { id: 11, name: 'Matchmaker' },
  { id: 12, name: 'Nightmare Knight' },
  { id: 13, name: 'Party Animal' },
  { id: 14, name: 'Secret Agent' },
  { id: 15, name: 'Talented Dancer' },
  { id: 16, name: 'Territorial' },
  { id: 17, name: 'Worm Whacker' },
  { id: 18, name: 'Allowance Collector' },
  { id: 19, name: 'Amateur Actor' },
  { id: 20, name: 'Animal Activist' },
  { id: 21, name: 'Beach Tamer' },
  { id: 22, name: 'Blessed!' },
  { id: 23, name: 'Exquisite Taste' },
  { id: 24, name: 'Fireworks in the Sky' },
  { id: 25, name: 'Greenhorn' },
  { id: 26, name: 'Jinx' },
  { id: 27, name: 'Lucid Dreamer' },
  { id: 28, name: 'Mathemagician' },
  { id: 29, name: 'Masquerader' },
  { id: 30, name: 'Ministrel' },
  { id: 31, name: 'Poet Laureate' },
  { id: 32, name: 'Quick as a Turtle' },
  { id: 33, name: 'Sea Scout' },
  { id: 34, name: 'Steampunked' },
  { id: 35, name: 'Superstitios' },
  { id: 36, name: 'The Milkman' },
  { id: 37, name: 'Turncoat' },
  { id: 38, name: 'Vive la Resistance' },
  { id: 39, name: 'Archpostman' },
  { id: 40, name: 'Clay Fighter' },
  { id: 41, name: 'Efreet Ally' },
  { id: 42, name: 'Ghostwisperer' },
  { id: 43, name: 'His True Face' },
  { id: 44, name: 'Ice Sculptor' },
  { id: 45, name: 'King Tibanus Fan' },
  { id: 46, name: 'Marblelous' },
  { id: 47, name: 'Marid Ally' },
  { id: 48, name: 'Passionate Kisser' },
  { id: 49, name: 'Perfect Fool' },
  { id: 50, name: 'Recognised Trader' },
  { id: 51, name: 'Rockstar' },
  { id: 52, name: 'Scrapper' },
  { id: 53, name: 'Vanity' },
  { id: 54, name: 'Wayfarer' },
  { id: 55, name: 'Champion of Chazorai' },
  { id: 56, name: 'Culinary Master' },
  { id: 57, name: 'Explorer' },
  { id: 58, name: 'Follower of Azerus' },
  { id: 59, name: 'Follower of Palimuth' },
  { id: 60, name: 'Friend of the Apes' },
  { id: 61, name: 'Golem in the Gears' },
  { id: 62, name: 'High-Flyer' },
  { id: 63, name: 'Interior Decorator' },
  { id: 64, name: 'Master Thief' },
  { id: 65, name: 'Polisher' },
  { id: 66, name: 'Potion Addict' },
  { id: 67, name: 'Ruthless' },
  { id: 68, name: "Ship's Kobold" },
  { id: 69, name: 'Top AVIN Agent' },
  { id: 70, name: 'Top CGB Agent' },
  { id: 71, name: 'Top TBI Agent' },
  { id: 72, name: 'Annihilator' },
  { id: 73, name: 'Castlemania' },
  { id: 74, name: 'Elite Hunter' },
  { id: 75, name: 'High Inquisitor' },
  { id: 76, name: 'Jamjam' },
  { id: 77, name: 'Lord of the Elements' },
  { id: 78, name: 'Warlord of Svargrond' },
  { id: 79, name: 'Master of the Nexus' },
  { id: 80, name: 'Razing!' },
  { id: 81, name: 'Dread Lord' },
  { id: 82, name: 'Lord Protector' },
  { id: 83, name: 'Herbicide' },
];
